services:
  - type: web
    name: medical-prediction-app
    env: python
    pythonVersion: 3.9.7
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn backend:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
